"""Play the world model like a snake game.

    python examples/play_wm.py --model marlenv/demodata/wm/model.pt

Arrow keys or WASD steer. The first frames come from the real simulator;
after that everything you see is generated by the world model, driven by
your keys alone.

Panels
    dream     what the model thinks you are looking at, rotated so north is
              up rather than left in the agent's turning frame
    canvas    those views stitched onto one map at their dead reckoned
              positions, fading with age -- the clearest read on whether the
              model keeps its geometry straight
    sim       the real simulator under the same actions, when --compare is on

Keys
    arrows / WASD   steer          space   pause
    TAB             raw <-> palette-snapped view
    G               save a gif of what has been shown
    R               restart from a fresh board
    [ / ]           fewer / more denoise steps
    ESC             quit
"""
import argparse
import os
import time

import numpy as np
import torch

import gymnasium as gym
import marlenv  # noqa: F401
from marlenv.core.palette import snap_to_palette
from marlenv.core.snake import Direction
from marlenv.grading.compare import PALETTE_SNAKES
from marlenv.wm.canvas import CanvasIntegrator, make_pose
from marlenv.wm.interactive import (SimulatorReference, WorldModelPlayer,
                                    world_up)
from marlenv.wm.model import WorldModel

REWARD_DICT = {'fruit': 1.0, 'kill': 0.0, 'lose': -5.0, 'win': 0.0,
               'time': 0.01}
BACKDROP = (18, 18, 22)
INK = (232, 232, 238)
MUTED = (140, 140, 150)


def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--model', default='marlenv/demodata/wm/model.pt')
    p.add_argument('--seed', type=int, default=0)
    p.add_argument('--bootstrap', type=int, default=1,
                   help='real frames fed in before the model takes over')
    p.add_argument('--denoise-steps', type=int, default=8)
    p.add_argument('--decay', type=float, default=0.95,
                   help='canvas fade per step; 1.0 keeps everything bright')
    p.add_argument('--tick-ms', type=int, default=180,
                   help='minimum milliseconds between moves')
    p.add_argument('--scale', type=int, default=34)
    p.add_argument('--canvas-scale', type=int, default=16)
    p.add_argument('--compare', action='store_true',
                   help='show the real simulator beside the dream')
    p.add_argument('--side', type=int, default=15)
    p.add_argument('--num-snakes', type=int, default=3)
    p.add_argument('--num-fruits', type=int, default=4)
    p.add_argument('--view-radius', type=int, default=4)
    p.add_argument('--obstacle-density', type=float, default=0.12)
    p.add_argument('--record', default=None,
                   help='write a gif here on exit')
    p.add_argument('--demo', type=int, default=0,
                   help='play N random moves headlessly and exit')
    p.add_argument('--device', default=None)
    return p.parse_args()


def load_model(path, device):
    state = torch.load(path, map_location='cpu', weights_only=False)
    model = WorldModel(view=state.get('view', 9), dim=state['dim'],
                       depth=state['depth'], heads=state['heads'])
    model.load_state_dict(state['model'])
    return model.to(device).eval(), state.get('context', 24)


def make_env(args):
    return gym.make(
        'Snake-v1', height=args.side, width=args.side,
        num_snakes=args.num_snakes, num_fruits=args.num_fruits,
        reward_dict=REWARD_DICT, view_radius=args.view_radius,
        observation_noise=2.0, snake_noise_sigma=8.0,
        background_gradient=16.0, obstacle_density=args.obstacle_density,
        disable_env_checker=True)


class Session:
    """One playthrough: env, model player, canvas and optional reference."""

    def __init__(self, args, model, context, device, seed):
        self.args = args
        self.env = make_env(args)
        self.env.reset(seed=seed)
        base = self.env.unwrapped
        snake = base.snakes[0]

        self.player = WorldModelPlayer(
            model, base.egocentric_rgb()[0], snake.direction,
            context=context, denoise_steps=args.denoise_steps,
            device=device, seed=seed,
            pose=make_pose(snake.head_coord[0], snake.head_coord[1],
                           snake.direction))
        self.canvas = CanvasIntegrator(args.side, args.side,
                                       args.view_radius, decay=args.decay)
        self.canvas.add(world_up(base.egocentric_rgb()[0], snake.direction),
                        self.player.pose)

        self.reference = SimulatorReference(self.env) if args.compare else None
        self.bootstrap(args.bootstrap)
        self.alive = True

    def bootstrap(self, frames):
        """Feed real transitions in before handing over to the model."""
        base = self.env.unwrapped
        for _ in range(max(0, frames - 1)):
            snake = base.snakes[0]
            if not snake.alive:
                break
            actions = [0] * base.num_snakes
            self.env.step(actions)
            snake = base.snakes[0]
            self.player.bootstrap([base.egocentric_rgb()[0]],
                                  [snake.direction], [0])
            self.canvas.add(world_up(base.egocentric_rgb()[0],
                                     snake.direction), self.player.pose)

    def step(self, cardinal):
        ego = self.player.step(cardinal)
        self.canvas.add(self.player.latest_frame(), self.player.pose)
        if self.reference is not None:
            self.alive = self.reference.step(ego)
        return ego


def compose(session, args, snapped):
    """Build the frame shown on screen, as a numpy image."""
    view = session.player.latest_frame()
    if snapped:
        view = snap_to_palette(view, PALETTE_SNAKES)
    panels = [('dream', np.repeat(np.repeat(view, args.scale, 0),
                                  args.scale, 1))]

    canvas = session.canvas.image
    panels.append(('canvas', np.repeat(np.repeat(canvas, args.canvas_scale,
                                                 0), args.canvas_scale, 1)))
    if session.reference is not None and session.reference.alive:
        real = session.reference.observation()
        if snapped:
            real = snap_to_palette(real, PALETTE_SNAKES)
        panels.append(('sim', np.repeat(np.repeat(real, args.scale, 0),
                                        args.scale, 1)))

    gap = 12
    height = max(image.shape[0] for _, image in panels)
    width = sum(image.shape[1] for _, image in panels) + gap * (len(panels)
                                                                - 1)
    sheet = np.zeros((height, width, 3), dtype=np.uint8)
    sheet[:] = BACKDROP
    x = 0
    for _, image in panels:
        sheet[:image.shape[0], x:x + image.shape[1]] = image
        x += image.shape[1] + gap
    return sheet, [name for name, _ in panels]


def run_demo(session, args, steps):
    """Headless self-play, so the pipeline can be checked without a screen."""
    rng = np.random.default_rng(args.seed)
    frames = []
    for _ in range(steps):
        session.step(list(Direction)[rng.integers(4)])
        frames.append(compose(session, args, snapped=True)[0])
    print(f'demo ran {steps} steps, canvas coverage '
          f'{session.canvas.coverage():.2f}')
    return frames


def save_gif(frames, path, duration=140):
    from PIL import Image
    if not frames:
        print('nothing to save')
        return
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    images = [Image.fromarray(frame) for frame in frames]
    images[0].save(path, save_all=True, append_images=images[1:],
                   format='GIF', loop=0, duration=duration)
    print(f'wrote {len(images)} frames to {path}')


def main():
    args = parse_args()
    device = args.device or ('cuda' if torch.cuda.is_available() else 'cpu')
    model, context = load_model(args.model, device)

    if args.demo:
        session = Session(args, model, context, device, args.seed)
        frames = run_demo(session, args, args.demo)
        if args.record:
            save_gif(frames, args.record)
        return

    import pygame
    pygame.init()
    pygame.display.set_caption('marlenv world model')
    font = pygame.font.SysFont('monospace', 15)

    session = Session(args, model, context, device, args.seed)
    sheet, names = compose(session, args, snapped=True)
    screen = pygame.display.set_mode((sheet.shape[1], sheet.shape[0] + 54))
    clock = pygame.time.Clock()

    keys = {pygame.K_UP: Direction.UP, pygame.K_w: Direction.UP,
            pygame.K_DOWN: Direction.DOWN, pygame.K_s: Direction.DOWN,
            pygame.K_LEFT: Direction.LEFT, pygame.K_a: Direction.LEFT,
            pygame.K_RIGHT: Direction.RIGHT, pygame.K_d: Direction.RIGHT}

    pending = None
    snapped = True
    paused = False
    frames = []
    last_move = 0.0
    running = True

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key in keys:
                    pending = keys[event.key]
                elif event.key == pygame.K_TAB:
                    snapped = not snapped
                elif event.key == pygame.K_SPACE:
                    paused = not paused
                elif event.key == pygame.K_g:
                    save_gif(frames, args.record or 'showcase/dream.gif')
                elif event.key == pygame.K_r:
                    session = Session(args, model, context, device,
                                      np.random.randint(1 << 30))
                    frames = []
                elif event.key in (pygame.K_LEFTBRACKET,
                                   pygame.K_RIGHTBRACKET):
                    delta = -1 if event.key == pygame.K_LEFTBRACKET else 1
                    session.player.denoise_steps = max(
                        1, session.player.denoise_steps + delta)

        now = time.time()
        if not paused and (now - last_move) * 1000 >= args.tick_ms:
            session.step(pending or session.player.heading)
            pending = None
            last_move = now

        sheet, names = compose(session, args, snapped)
        frames.append(sheet)
        surface = pygame.surfarray.make_surface(sheet.swapaxes(0, 1))
        screen.fill(BACKDROP)
        screen.blit(surface, (0, 0))

        status = (f'step {session.player.steps}   '
                  f'facing {session.player.heading.name.lower()}   '
                  f'denoise {session.player.denoise_steps}   '
                  f'coverage {session.canvas.coverage():.2f}   '
                  f'{"PAUSED" if paused else f"{clock.get_fps():.0f} fps"}')
        screen.blit(font.render(status, True, INK), (8, sheet.shape[0] + 8))
        screen.blit(font.render('  '.join(names), True, MUTED),
                    (8, sheet.shape[0] + 30))
        pygame.display.flip()
        clock.tick(60)

    if args.record:
        save_gif(frames, args.record)
    pygame.quit()


if __name__ == '__main__':
    main()
